name: weather_app
description: "This is an sample of weather app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  intl: ^0.20.1
  pull_to_refresh_flutter3: ^2.0.2

  domain:
    path: packages/domain
  datasource:
    path: packages/datasource

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.0.0
  mockito: ^5.4.3
  test: ^1.16.4
  bloc_test: ^9.0.0

flutter:

  uses-material-design: true